apiVersion: apps/v1
kind: Deployment
metadata:
  name: sachin-deployment
  labels:
    app: webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sachin
  template:
    metadata:
      labels:
        app: sachin
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000